module Lowmu
  module Commands
    class Configure
      CONFIG_TEMPLATE = <<~YAML
        # lowmu configuration file
        # Generated by `lowmu configure`

        # Directory where generated content is stored
        content_dir: ~/projects/lowmu/content

        # LLM configuration for AI-assisted content generation
        llm:
          provider: anthropic
          model: claude-opus-4-6

        # Publishing targets
        targets:
          - name: my-hugo-blog
            type: hugo
            base_url: https://example.com
            base_path: ~/projects/my-blog/content

          - name: substack
            type: substack
            auth:
              type: api_key
              api_key: your_key_here  # or set LOWMU_SUBSTACK_API_KEY

          - name: mastodon
            type: mastodon
            base_url: https://mastodon.social
            auth:
              type: oauth
              access_token: your_token_here  # or set LOWMU_MASTODON_ACCESS_TOKEN

          - name: linkedin
            type: linkedin  # generate-only, no auth needed
      YAML

      def initialize(path = Config::DEFAULT_PATH)
        @path = File.expand_path(path)
      end

      def call
        if File.exist?(@path)
          {exists: true, path: @path}
        else
          FileUtils.mkdir_p(File.dirname(@path))
          File.write(@path, CONFIG_TEMPLATE)
          {created: true, path: @path}
        end
      end
    end
  end
end
